### PR TITLE
Alternate

### PR DESCRIPTION
**Pull request by martindurant**
My simplistic old-fashioned rewrite. Note that these is no example or test for branched, so I don't know how this ought to look. lazy/call things are not addressed, and I did not change tests in test_spec to comply.

### CODE REVIEW

**Comment by martindurant** [comment]
cc @isidentical , in case this didn't alert for you

**Comment by isidentical** [comment]
I don't have any strong preference, and it seems like this version also sustains the needs but I am wondering what are the advantages? The current version is extremely simple to use, especially when it comes to integrating existing hooks, and it also doesn't limit us into using a pre-defined number of hooks.

**Comment by isidentical** [comment]
@martindurant if you feel strong about this, we can also go with it. By the way if you could make a new s3fs release sometime soon, it would be really nice (not fsspec or gcsfs, but only s3fs including my last PR).

**Comment by martindurant** [comment]
I am releasing all three together these days, to remove version ambiguity. I any case, there always seem to be some improvements in all three worth pushing out.

I'll get back to you later with more detail about why I prefer my version of this code; but such a thing can come down to personal preference (what seems simpler to me may not to anyone else). What we most need are examples of usage, that might make the situation clearer for all.

**Comment by isidentical** [comment]
> I am releasing all three together these days, to remove version ambiguity. 

Yeah, but with these callbacks being merged now making a release would restrict us to stick with the current form. 

> What we most need are examples of usage, that might make the situation clearer for all.

Definitely! I can come up with a couple examples (even default ones), but first we need to make them supported by downstream implementations (e.g s3fs) otherwise they are not going to be useful. I for example implemented the callbacks to `sshfs`, and here how it looks;

**Comment by isidentical** [comment]
If you compare this with the one you have, you'll see the major difference the callbacks that I proposed and your alternative is that the version I proposed is trying to decouple the actual progress managing logic from the callback system. It is merely a bridge. Here is the DotPrinter;
```py
import fsspec
from sshfs import SSHFileSystem

class DotPrinter:
    def __init__(self):
        self.total_size = None
        self.current_progress = 0

    @property
    def percentage(self):
        return round(self.current_progress / self.total_size * 100)

    def refresh(self):
        if self.total_size is not None:
            bar = "["
            bar += "x" * self.percentage
            bar += "." * (100 - self.percentage)
            bar += f"] ({self.current_progress}/{self.total_size})"
        else:
            bar += "."
        print(bar, end="\r")

    def set_size(self, size):
        self.total_size = size
        self.refresh()

    def absolute_update(self, amount):
        self.current_progress = amount
        self.refresh()

    def relative_update(self, amount):
        self.absolute_update(self.current_progress + amount)

    def as_callback(self):
        return fsspec.callback(
            set_size=self.set_size,
            relative_update=self.relative_update,
            absolute_update=self.absolute_update
        )
```

[asciicast](https://asciinema.org/a/9OyReuTuPk1TrBBOSvVgoHHKb)

And the usage is like this;
```py
import fsspec

fs = fsspec.filesystem('<something>')
dot_printer = DotPrinter()
fs.get_file(
    "/home/isidentical/disk/tmp_file", 
    "/home/isidentical/disk/tmp_file2",
    callback=dot_printer.as_callback()
)
```

**Comment by isidentical** [comment]
CC: @martindurant

**Comment by martindurant** [comment]
Yeah, I guess I am having a hard time describing my discomfort with the code above - which may well mean that my feeling is misplaced. The part that strikes me as weird is `as_callback`, which takes our class instance and makes a different instance out of it, whose methods are methods of the original instance. In my model, you do this by subclassing (which would mean `callback=DotPrinter()`). To decouple how it gets called and how the state is represented, you could always do mixins (depending how many types we might eventually have).

Question: what "hooks" do you imagine could possibly exist beyond the current ones in DotPrinter? There would be a loose coupling between the set of hooks that a given FS implementation calls and the set of hooks that a particular callback class implements (a callback having hooks that might not get called and a FS that calls hooks that do nothing).

In any case, I think your example and how to call it needs to be in the docs for callbacks to be useful to people in general. That example, with the video for one file and multiple files, with one of the builtin FS implementations would be ideal.

**Comment by isidentical** [comment]
> To decouple how it gets called and how the state is represented, you could always do mixins (depending how many types we might eventually have).

The problem with that is, there is no need to re-implement a new class every time you need to connect hooks to your existing system. That is why I decided to with this approach since callbacks have no connection to progress bars themselves (which might not be the actual use case).

> Question: what "hooks" do you imagine could possibly exist beyond the current ones in DotPrinter?

When I was drafting the proposal, I was able to use the same set of hooks for all of the *current* APIs, but as I stated previously, callbacks are not progress handlers so I don't think we should restrict them to that purpose. 

> In any case, I think your example and how to call it needs to be in the docs for callbacks to be useful to people in general. That example, with the video for one file and multiple files, with one of the builtin FS implementations would be ideal.

I would be happy to do so after we decide how we want to go. I understand your discomfort, and I tried to explain my reasoning as best as I can but after this point feel free to make the final judgement. I'd really want to see one form or another in a released fsspec version, and finally integrate these stuff into the downstream projects.

**Comment by martindurant** [comment]
(I have some personal stuff this morning, I'll make that decision later today)

**Comment by martindurant** [comment]
OK, so I think we should use my formalism. Sorry for all the back and forth! 
That means that all callbacks should be a subclass or otherwise implement a base class (similar to what I have here), and we specify the expected methods.

Note that this does still allow for additional methods on specialised subclasses. We could even add the following to the no-op base class, to indicate this possibility, and safely skip calls to methods that don't exist on a class.

```python
    def no_op(self, *_, **__):
         pass

    def __getattr__(self, item):
        return self.no_op
```

Also, we *could* implement lazy operations on the base class
```python
    def lazy(self, methname, func, *args, extra_kwargs=None, **kwargs):
        if hasattr(self, methname):
             return getattr(self, methname)(func(*args, **kwargs), **(extra_kwargs or {}))
```
(i.e., does nothing if the method doesn't exist)

I feel like this fits all my structural requirements and also fulfills all of the possible requirements you are after. 

Would you take on implementing this version of callbacks?

**Comment by isidentical** [comment]
> Would you take on implementing this version of callbacks?

What is missing from the demo you have? I guess it would be faster if you could convert this to a PR against fsspec master and then we can proceed there.

**Comment by martindurant** [comment]
I have to go through all the places the callback is referenced and change to the new signature as well as maybe implement what I said above.

I am suffering after-vaccine today, but maybe I can get to it later.

On July 9, 2021 3:52:06 AM EDT, Batuhan Taskaya ***@***.***> wrote:
>> Would you take on implementing this version of callbacks?
>
>What is missing from the demo you have? I guess it would be faster if
>you could convert this to a PR against fsspec master and then we can
>proceed there. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/isidentical/filesystem_spec/pull/2#issuecomment-876990439

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
The example you had above doesn't include a `branch` call - do you happen to have any code example of how you pictured branching working?

**Comment by isidentical** [comment]
See put/get on both abstract and async filesystems. Also may I suggest you
separate it from the actual Callback object to a separate function since it
is not something that you are supposed to override.

**Comment by martindurant** [comment]
I see 
```python
    def _put(...):
        ....
        callback.call("set_size", len(files))
        for lpath, rpath in zip(files, rpaths):
            branch(callback, lpath, rpath, kwargs)
```
which mutates `kwargs` in function
```python
def branch(...):
    ...
    branched = callback.call("branch", path_1, path_2)
    ...
    if kwargs is not None:
        kwargs["callback"] = branched
```
but no example of what a `branch` function/hook (the thing that gets called above) would actually look like. That's what I'm after.

**Comment by isidentical** [comment]
We have a test for it. Branch is basically what creates sub progress bars.
So when you do a put(), you get an overall progress bar like 5/25 files,
and for each file you are transferring (either as single or concurrently)
at that moment, you get a branch call which creates the actual transfer
progress (e.g 500/2500 bytes are transffered). I am out of pc right now,
but you should be able to find the example among the tests I added

**Pull request closed without merging**
